# Numpy

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


Create a NumPy array with values [10, 20, 30, 40]

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


Print the type of the array

In [3]:
type(arr1)

numpy.ndarray

Create a 2D Array

In [4]:
arr2 = np.array([[50,60,70],[80,90,100]])
print(arr2)

[[ 50  60  70]
 [ 80  90 100]]


Find - shape
dimension
size
datatype

In [5]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

(2, 3)
2
6
int64


Create Zero Matrix

In [7]:
arr3 = np.zeros((3,2))
print(arr3)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
print(arr3.dtype)

int64


In [10]:
arr3 = arr3.astype(int)

In [13]:
print(arr3.dtype)

int64


Create a 2x4 array of ones

In [14]:
arr4 = np.ones((2,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create a 2x2 array filled with value 7

In [15]:
arr5 = np.full((2,2),7)
print(arr5)

[[7 7]
 [7 7]]


Generate 5 random numbers between 0 and 1

In [18]:
print(np.random.rand(5))

[0.67761645 0.47573862 0.69463018 0.26534269 0.04854291]


Using arange Create numbers from 1 to 10

In [19]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


Create even numbers between 10 and 20

In [20]:
print(np.arange(10,21,2))

[10 12 14 16 18 20]


Create 5 evenly spaced values between 0 and 1

In [22]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


Indexing

In [23]:
arr = np.array([10,20,30,40])

In [24]:
print(arr[0])

10


In [25]:
print(arr[1])

20


In [26]:
print(arr[-1])

40


In [39]:
arr7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(arr7[0:2, 0:2])

[[1 2]
 [4 5]]


In [32]:
print(arr7[0:2, 1:3])

[[2 3]
 [5 6]]


In [33]:
print(arr7[1:, 0:2])

[[4 5]
 [7 8]]


In [34]:
print(arr7[1:, 1:])

[[5 6]
 [8 9]]


In [35]:
print(arr7[0, :])

[1 2 3]


In [36]:
print(arr7[:, 0])

[1 4 7]


In [38]:
print(np.diag(arr7))

[1 5 9]


Convert 1D to 2D Array

In [45]:
arr9 = np.array([1,2,3,4,5,6])
print(arr9)
arr9 = arr9.reshape(3,2)
print(arr9)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


Looping through array

In [47]:
arr8 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr8)
for i in arr8:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


Add 10 to Each Element

In [48]:
print(arr8 + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


Multiply Arrays

In [49]:
x = np.array([[1,2], [3,4]])
y = np.array([[1,2], [3,4]])
print(x*y)

[[ 1  4]
 [ 9 16]]


In [50]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr4*arr5)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
arr4 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr4@arr5)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Find mean, median, mode, max, min

In [53]:
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))

25.0
25.0
40
10


In [54]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
arr1 = np.array([10,10,10,20,30])
from scipy import stats
print(stats.mode(arr1))

ModeResult(mode=np.int64(10), count=np.int64(3))


You have marks of students:

marks = [45, 78, 90, 66, 88, 72, 59]
Tasks:  
Convert to NumPy array  
Find average marks  
Find highest & lowest marks  
Find students scoring above average  
Add 5 grace marks to all students

In [4]:
marks = np.array([45, 78, 90, 66, 88, 72, 59])
print("Average is :", np.mean(marks))
print("Highest Marks :", np.max(marks))
print("Lowest Marks :", np.min(marks))
print("After adding 5 grace marks :", marks + 5)
print("Above average marks :", marks[marks>np.mean(marks)])       # Filtering

Average is : 71.14285714285714
Highest Marks : 90
Lowest Marks : 45
After adding 5 grace marks : [50 83 95 71 93 77 64]
Above average marks : [78 90 88 72]


Temperature recorded for 7 days:

temps = [30, 32, 35, 31, 29, 40, 38]
Tasks:  
Find days with temperature > 35  
Count number of hot days   

In [7]:
temp = np.array([30, 32, 35, 31, 29, 40, 38])
hot_days = temp[temp>35]
print(len(hot_days))

2


Employee salaries:  

salary = [25000, 40000, 35000, 50000, 45000]
Tasks:  
Increase all salaries by 10%  
Find employees earning > 40000   

In [2]:
salary = np.array([25000, 40000, 35000, 50000, 45000])
print("10% increased salary :", salary + salary*0.1)
print("Employees earning > 40000 :", salary>40000)

10% increased salary : [27500. 44000. 38500. 55000. 49500.]
Employees earning > 40000 : [False False False  True  True]


A grayscale image (3x3 pixels):

img = [[100, 150, 200],
       [50, 75, 125],
       [0, 25, 255]]
Tasks:  
Convert to NumPy array  
Increase brightness by 20  
Clip values to max 255  

In [10]:
img = np.array([[100, 150, 200], [50, 75, 125], [0, 25, 255]])
print(img)
print("Increased brightness :", img + 20)
clipped = np.clip(img, 0, 255)
print("Clipped values to 255 :", clipped)

[[100 150 200]
 [ 50  75 125]
 [  0  25 255]]
Increased brightness : [[120 170 220]
 [ 70  95 145]
 [ 20  45 275]]
Clipped values to 255 : [[100 150 200]
 [ 50  75 125]
 [  0  25 255]]


Sales for 5 days:

sales = [200, 300, 250, 400, 350]
Tasks:  
Find total sales  
Find day with highest sales  
Find days where sales < 300  

In [15]:
sales = np.array([200, 300, 250, 400, 350])
print("Total sales :", np.sum(sales))
print("Highest sales :", np.max(sales))
print("Sales < 300 :", sales<300)

Total sales : 1500
Highest sales : 400
Sales < 300 : [ True False  True False False]


Scores:

scores = [55, 65, 75, 85, 95]
Tasks:  
Get students with grades ≥ 75  
Replace scores < 60 with 60  

In [17]:
scores = np.array([55, 65, 75, 85, 95])
print("Students with grade >= 75 :", scores>=75)

Students with grade >= 75 : [False False  True  True  True]


In [18]:
scores[scores < 60] = 60
print("Scores after replacing <60 with 60 :", scores)

Scores after replacing <60 with 60 : [60 65 75 85 95]
